server:
  port: 8100

spring:
  application:
    name: spring-boot-camunda-demo
  datasource:
    #如果没有自动生成表，在数据库连接后加   &nullCatalogMeansCurrent=true
    url: jdbc:mysql://127.0.0.1:3306/camunda?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nopasswd1
camunda.bpm:
  # 配置账户密码来访问Camunda自带的管理界面
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  #禁止自动部署resources下面的bpmn文件
  auto-deployment-enabled: true
  #禁止index跳转到Camunda自带的管理界面，默认true
  #    webapp:
  #      index-redirect-enabled: false

